AllCops:
  TargetRubyVersion: 2.4

inherit_gem:
  ruboconfig: rubocop.yml

Style/MutableConstant:
  Exclude:
    - app/constants/api.rb

Metrics/AbcSize:
  Exclude:
    - app/routes/single_coach_middleware/attendees/show.rb

Metrics/MethodLength:
  Exclude:
    - app/routes/single_coach_middleware/attendees/show.rb