version: 2
jobs:
  build:
    working_directory: ~/coach_demo
    docker:
      - image: circleci/ruby:2.4.2-node
        environment:
          RAILS_ENV: test
    steps:
      - checkout

      - type: cache-restore
        key: coach-demo-{{ checksum "Gemfile.lock" }}

      - run: bundle install --path vendor/bundle

      - type: cache-save
        key: coach-demo-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load

      - type: shell
        command: |
          bundle exec rspec --profile 10 \
                            --format RspecJunitFormatter \
                            --out /tmp/test-results/rspec.xml \
                            --format progress \
                            $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)

      - type: shell
        command: |
          bundle exec rubocop

      # Save artifacts
      - type: store_test_results
        path: /tmp/test-results
